version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: fituska_php73
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
  
  mysql:
    container_name: fituska_mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fituska
    ports:
      - 6033:3306
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    container_name: fituska_phpmyadmin
    image: phpmyadmin:5.1
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80

volumes:
  mysql_data:
